version: "3.8"

services:
  mongo1:
    image: mongo:latest
    container_name: mongo1
    command: >
      bash -c "
      chmod 400 /opt/keyfiles/mongo-keyfile && 
      mongod --replSet rs0 --bind_ip_all --keyFile /opt/keyfiles/mongo-keyfile
      "
    volumes:
      - mongo1data:/data/db
      - mongo1config:/data/configdb
      - ./infrastructure/mongodb/mongo-keyfile:/opt/keyfiles/mongo-keyfile
    ports:
      - 27017:27017
  mongo2:
    image: mongo:latest
    container_name: mongo2
    command: >
      bash -c "
      chmod 400 /opt/keyfiles/mongo-keyfile && 
      mongod --replSet rs0 --bind_ip_all --keyFile /opt/keyfiles/mongo-keyfile
      "
    volumes:
      - mongo2data:/data/db
      - mongo2config:/data/configdb
      - ./infrastructure/mongodb/mongo-keyfile:/opt/keyfiles/mongo-keyfile
    ports:
      - 27018:27017
  mongo3:
    image: mongo:latest
    container_name: mongo3
    command: >
      bash -c "
      chmod 400 /opt/keyfiles/mongo-keyfile && 
      mongod --replSet rs0 --bind_ip_all --keyFile /opt/keyfiles/mongo-keyfile
      "
    volumes:
      - mongo3data:/data/db
      - mongo3config:/data/configdb
      - ./infrastructure/mongodb/mongo-keyfile:/opt/keyfiles/mongo-keyfile
    ports:
      - 27019:27017

volumes:
  mongo1data:
  mongo1config:
  mongo2data:
  mongo2config:
  mongo3data:
  mongo3config:
