version: "3.8"

services:
  mongo1:
    image: mongo:latest
    command: >
      bash -c "
      chmod 400 /opt/keyfiles/mongo-keyfile && 
      mongod --replSet rs0 --bind_ip_all --keyFile /opt/keyfiles/mongo-keyfile
      "
    volumes:
      - mongo1data:/data/db
      - ./mongo-keyfile:/opt/keyfiles/mongo-keyfile
    environment:
      - MONGO_INITDB_ROOT_USERNAME=your_username
      - MONGO_INITDB_ROOT_PASSWORD=your_password
    ports:
      - 27017:27017
  mongo2:
    image: mongo:latest
    command: >
      bash -c "
      chmod 400 /opt/keyfiles/mongo-keyfile && 
      mongod --replSet rs0 --bind_ip_all --keyFile /opt/keyfiles/mongo-keyfile
      "
    volumes:
      - mongo2data:/data/db
      - ./mongo-keyfile:/opt/keyfiles/mongo-keyfile
    environment:
      - MONGO_INITDB_ROOT_USERNAME=your_username
      - MONGO_INITDB_ROOT_PASSWORD=your_password
    ports:
      - 27018:27017
  mongo3:
    image: mongo:latest
    command: >
      bash -c "
      chmod 400 /opt/keyfiles/mongo-keyfile && 
      mongod --replSet rs0 --bind_ip_all --keyFile /opt/keyfiles/mongo-keyfile
      "
    volumes:
      - mongo3data:/data/db
      - ./mongo-keyfile:/opt/keyfiles/mongo-keyfile
    environment:
      - MONGO_INITDB_ROOT_USERNAME=your_username
      - MONGO_INITDB_ROOT_PASSWORD=your_password
    ports:
      - 27019:27017

volumes:
  mongo1data:
  mongo2data:
  mongo3data:
